export const recipesActionTypes = {
    'RECIPES_FETCHING_START':'RECIPES_FETCHING_START',
    'RECIPES_FETCHING_SUCCESS':'RECIPES_FETCHING_SUCCESS',
    'RECIPES_FETCHING_FAILURE':'RECIPES_FETCHING_FAILURE',
}
